# Generated by Django 2.2.7 on 2020-05-04 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
